options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://cloudbuild-logs-wakos

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/wako-docker/web:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/wako-docker/web:latest']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/wako-docker/web:latest'
