version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echoa install -aws cliente
      - checkout
      - run: ls -la

jobs:
  install-dependencias:
    docker:
      - image: cimg/base:stable
    steps:
      - install-aws-cli

workflows:
  workflow1:
    jobs:
      - install-dependencias
