version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.1
  docker: circleci/docker@2.0.0 
commands:
  install-aws-cli:
    steps:
      - run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

jobs:
  install-dependencias:
    executor: aws-cli/default
    docker:
      - image: cimg/base:stable
    steps:
      - run: aws-cli/default
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run : docker build -t $DOCKERHUB_USERNAME/circle-ci .
      - run : docker push $DOCKERHUB_USERNAME/circle-ci:latest    





workflows:
  workflow1:
    jobs:
      - install-dependencias:
         context: aws-credential
       
        
