version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  docker: circleci/docker@2.8.2



jobs:
  aws:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: aws sts get-caller-identity
  docker:
    executor: docker/machine 
    steps:
      - docker/install-docker
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run : docker build -t $DOCKERHUB_USERNAME/circle-ci .
      - run : docker push $DOCKERHUB_USERNAME/circle-ci:latest


workflows:
  workflow1:
    jobs:
      - aws:
          context: aws-credential
      - docker:
         context: docker-credential  