version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echo install -aws cliente
      - checkout
      - run: ls -la
      - run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

jobs:
  install-dependencias:
    docker:
      - image: cimg/base:stable
    steps:
      - install-aws-cli
      - setup_remote_docker:
          docker_layer_caching: true

workflows:
  workflow1:
    jobs:
      - install-dependencias
