version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.3.2
  docker: circleci/docker@2.0.0 

jobs:
  all:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: Get AWS caller identity
          command: |
            if [ -z "$AWS_REGION" ] || [ "$AWS_REGION" = "" ]; then
              echo "AWS_REGION is not set. Defaulting to us-east-1."
              export AWS_REGION=us-east-1
            fi
            aws sts get-caller-identity

workflows:
  workflow1:
    jobs:
      - all:
          context: aws-credential
