version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.1
  docker: circleci/docker@2.0.0 

jobs:
  all:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: aws sts get-caller-identity


workflows:
  workflow1:
    jobs:
      - all:
          context: aws-credential