version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  docker: circleci/docker@2.8.2



jobs:
  aws:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: aws sts get-caller-identity
  docker:
    executor: docker/machine 
    steps:
      - checkout
      - docker/install-docker
      - run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker/build:
          image: webcircle
          tag: latest
          dockerfile: Dockerfile
      - docker/push:
          image: webcircle
          tag: latest
          registry: wako1982/circle-ci
             


workflows:
  workflow1:
    jobs:
      - aws:
          context: aws-credential
      - docker:
         context: docker-credential  